services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - main-service
      - log-service
    
  main-service:
    build:
      context: ./main-service
    ports:
      - "8000:8000"
    environment:
      - LOG_SERVICE_URL=http://log-service:8002
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/firebase-sa
    depends_on:
      - log-service
    secrets:
      - firebase-sa

  log-service:
    build:
      context: ./log-service
    ports:
      - "8002:8002"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/firebase-sa
    secrets:
      - firebase-sa

  consulta-natural-service:
    build:
      context: ./consulta-natural-service
    ports:
      - "8003:8003"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/firebase-sa
    secrets:
      - firebase-sa
    depends_on:
      - log-service

secrets:
  firebase-sa:
    file: ./service-account.json
