version: '3.8'

services:
  main-service:
    build: ./main-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/personas
      - LOG_SERVICE_URL=http://log-service:8002
    depends_on:
      - db
      - log-service

  query-service:
    build: ./Final_Dise-o2/query-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/personas
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db

  log-service:
    build: ./Final_Dise-o2/log-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/personas
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=personas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./Final_Dise-o2/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - main-service
      - query-service
      - log-service

volumes:
  postgres_data: 
